sudo: required

language: bash

services:
  - docker

branches:
  only:
  - master

script:
    - pwd && ls -ltr

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push vitalyb/python-app;
