sudo: required

language: bash

services:
  - docker

script:
    - echo $DOCKER_USERNAME

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      docker push vitalyb/python-app;
      fi
